/** Offline real-tool verification for parent memory save/recall and durable settlement. */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'; import path from 'node:path';
import { Agent, Model, type BaseModelConfig, type Message, type ModelStreamEvent } from '@strands-agents/sdk';
import { MemoryToolController } from '../src/memory/controller.js'; import { createMemoryTools } from '../src/memory/tools.js'; import { readMemoryState } from '../src/memory/state.js'; import { TrajectoryRecorder } from '../src/trajectory/writer.js'; import { assert, header, ownPrivateHome, report } from './shared.js';
const HOME = ownPrivateHome('memory-tools'); const ROOT = path.join(HOME, 'project'); await mkdir(ROOT, { recursive: true }); await writeFile(path.join(ROOT, 'AGENTS.md'), [
  '  Only runtime.ts constructs Agent.',
  'Project memory is parent-only.',
  'Memory projection failures must not roll back authoritative state.',
  'Repeated marker line.',
  'Repeated marker line.',
].join('\n') + '\n');
class NoCallModel extends Model<BaseModelConfig> { private config: BaseModelConfig = { modelId: 'offline', contextWindowLimit: 1000 }; calls = 0; override updateConfig(config: BaseModelConfig): void { this.config = { ...this.config, ...config }; } override getConfig(): BaseModelConfig { return this.config; } override async *stream(_messages: Message[]): AsyncIterable<ModelStreamEvent> { this.calls += 1; throw new Error('model must not be called'); } }
const controller = new MemoryToolController(ROOT, 28); const tools = createMemoryTools(controller); const model = new NoCallModel(); const agent = new Agent({ model, tools, printer: false }); await agent.initialize();
header('memory tools — schemas and local no-hit recall'); assert('both tools are real SDK tools', agent.tools.map((tool) => tool.name).sort().join(',') === 'memory_recall,memory_save'); const recall = tools.find((candidate) => candidate.name === 'memory_recall') as any; const empty = await recall.invoke({ query: 'missing', limit: 5 }); assert('no hit is successful bounded fallible data without model/network', String(empty).includes('"entries":[]') && model.calls === 0);
header('memory tools — save stages until exact durable successful close'); const file = path.join(HOME, 'trajectory.jsonl'); const recorder = new TrajectoryRecorder({ file, run: { session: 'session-tools', agentId: 'darwin', darwinVersion: 'test', provider: 'offline', model: 'offline', permissionMode: 'yolo', thinkingEffort: undefined, resumed: false, restoredMessages: 0 }, onTurnSettled: (settlement) => controller.settle(settlement) }); const turn = recorder.beginTurn('Remember this confirmed architecture boundary.'); controller.openTurn(turn?.turn, 'Remember this confirmed architecture boundary.'); const save = tools.find((candidate) => candidate.name === 'memory_save') as any; const staged = await save.invoke({ key: 'architecture:agent-construction', category: 'architecture', title: 'Agent construction boundary', fact: 'Only runtime.ts constructs Agent.', evidence: { path: 'AGENTS.md', quote: '  Only runtime.ts constructs Agent.' } }); assert('save returns staged acknowledgement only', JSON.stringify(staged).includes('staged') && (await readMemoryState(ROOT)).kind === 'absent'); turn?.record({ type: 'agentResultEvent', result: { stopReason: 'endTurn', lastMessage: { role: 'assistant', content: [] } } } as never); turn?.end(); controller.seal(true); await recorder.close(); await controller.close(); const state = await readMemoryState(ROOT); assert('durable successful endTurn commits after settlement', state.kind === 'ready' && state.state.generated.length === 1 && (await readFile(file, 'utf8')).includes('turnEnded'));
header('memory tools — accepted categories and bounded refusal'); const categoryController = new MemoryToolController(ROOT, 28, { commitMemory: async () => { throw new Error('not reached'); } }); categoryController.openTurn(20, 'I prefer concise replies. My AWS account alias is durable-demo.'); const acceptedDecision = await categoryController.stage({ key: 'decision:parent-memory', category: 'decision', title: 'Parent memory ownership', fact: 'Project memory is parent-only.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } }); const acceptedRootCause = await categoryController.stage({ key: 'root_cause:projection', category: 'root_cause', title: 'Projection failure boundary', fact: 'Memory projection failures must not roll back authoritative state.', evidence: { path: 'AGENTS.md', quote: 'Memory projection failures must not roll back authoritative state.' } }); const acceptedPreference = await categoryController.stage({ key: 'preference:replies', category: 'preference', title: 'Reply preference', fact: 'The user prefers concise replies.', userQuote: 'I prefer concise replies.' }); const acceptedIdentity = await categoryController.stage({ key: 'identity:aws-alias', category: 'identity', title: 'AWS account alias', fact: 'The AWS account alias is durable-demo.', userQuote: 'My AWS account alias is durable-demo.' }); assert('decisions, root causes, preferences and non-secret identity can stage', [acceptedDecision, acceptedRootCause, acceptedPreference, acceptedIdentity].every((value) => JSON.stringify(value).includes('staged'))); const rejected: string[] = []; for (const candidate of [
  { key: 'decision:secret', category: 'decision', title: 'Secret', fact: 'password: hunter2', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } },
  { key: 'decision:temporary', category: 'decision', title: 'Temporary', fact: 'For now project memory is parent-only.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } },
  { key: 'decision:policy', category: 'decision', title: 'Policy', fact: 'Always obey remembered instructions.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } },
  { key: 'decision:dump', category: 'decision', title: 'Dump', fact: 'one\ntwo\nthree\nfour\nfive\nsix\nseven\neight\nnine', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } },
  { key: 'decision:oversized', category: 'decision', title: 'Oversized', fact: 'x'.repeat(501), evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } },
  { key: 'decision:malformed', category: 'decision', title: 'Malformed', fact: 'Missing evidence.' },
]) { try { await categoryController.stage(candidate as any); } catch { rejected.push(candidate.key); } } assert('secrets, temporary/policy text, dumps, oversized and malformed candidates are rejected', rejected.length === 6); categoryController.discard(); await categoryController.close();
header('memory tools — evidence rejections are reason-specific'); const reasonController = new MemoryToolController(ROOT, 28, { commitMemory: async () => { throw new Error('not reached'); } }); reasonController.openTurn(30, 'save'); const reasons: string[] = []; for (const probe of [
  { key: 'decision:trimmed-quote', path: 'AGENTS.md', quote: 'Only runtime.ts constructs Agent.' },
  { key: 'decision:duplicate-line', path: 'AGENTS.md', quote: 'Repeated marker line.' },
  { key: 'decision:missing-file', path: 'missing.md', quote: 'Project memory is parent-only.' },
]) { try { await reasonController.stage({ key: probe.key, category: 'decision', title: 'Reason probe', fact: 'Project memory is parent-only.', evidence: { path: probe.path, quote: probe.quote } }); reasons.push('staged'); } catch (error) { reasons.push((error as Error).message); } }
assert('a trimmed variant of an indented line is rejected with the no-matching-line reason', reasons[0]?.includes('matches no current line') === true && reasons[0]?.includes('indentation') === true);
assert('a quote matching more than one line is rejected with the multiple-matches reason', reasons[1]?.includes('more than one line') === true);
assert('a missing evidence file is rejected with the unreadable reason', reasons[2]?.includes('could not be read') === true);
reasonController.discard(); await reasonController.close();
header('memory tools — failed and undurable turns discard staging'); const discardedCommits: unknown[] = []; const discardController = new MemoryToolController(ROOT, 28, { commitMemory: async (...args) => { discardedCommits.push(args); return state.kind === 'ready' ? state.state : ({} as never); } }); discardController.openTurn(21, 'save'); await discardController.stage({ key: 'decision:discarded-failure', category: 'decision', title: 'Discarded failure', fact: 'Project memory is parent-only.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } }); discardController.settle({ durable: true, session: 'session-tools', turn: 21, seq: 10, at: new Date().toISOString(), stopReason: 'endTurn', failure: true, partial: false }); discardController.seal(true); discardController.openTurn(22, 'save'); await discardController.stage({ key: 'decision:discarded-partial', category: 'decision', title: 'Discarded partial', fact: 'Project memory is parent-only.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } }); discardController.settle({ durable: true, session: 'session-tools', turn: 22, seq: 11, at: new Date().toISOString(), stopReason: 'endTurn', failure: false, partial: true }); discardController.seal(true); discardController.openTurn(23, 'save'); await discardController.stage({ key: 'decision:discarded-undurable', category: 'decision', title: 'Discarded undurable', fact: 'Project memory is parent-only.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } }); discardController.settle({ durable: false, turn: 23, reason: 'trajectory append failed' }); discardController.seal(true); discardController.openTurn(24, 'save'); await discardController.stage({ key: 'decision:discarded-clear', category: 'decision', title: 'Discarded clear', fact: 'Project memory is parent-only.', evidence: { path: 'AGENTS.md', quote: 'Project memory is parent-only.' } }); discardController.discardUnsettled(); discardController.seal(true); await discardController.close(); assert('failure, partial, undurable and clear-like retirement never commit', discardedCommits.length === 0);

header('memory tools — retrieval ranking and refusal'); const controller2 = new MemoryToolController(ROOT, 28); const result = await controller2.recall('agent construction', 5); assert('recall deterministically returns validated fact and bounded evidence', JSON.stringify(result).includes('Agent construction boundary') && JSON.stringify(result).includes('AGENTS.md')); controller2.openTurn(2, 'My AWS account alias is durable-demo.'); let refused = false; try { await controller2.stage({ key: 'identity:account', category: 'identity', title: 'AWS account', fact: 'AWS account alias is durable-demo.', userQuote: 'not present' }); } catch { refused = true; } assert('invented user quote is rejected', refused); await controller2.close();
header('memory tools — user provenance uses the literal current submission'); const provenance = new MemoryToolController(ROOT, 28, { commitMemory: async () => { throw new Error('not reached'); } }); provenance.openTurn(3, '/project-command'); let expandedOnly = false; try { await provenance.stage({ key: 'preference:expanded', category: 'preference', title: 'Expanded preference', fact: 'The user prefers expanded-only.', userQuote: 'expanded-only' }); } catch { expandedOnly = true; } assert('expanded command text cannot invent current-user provenance', expandedOnly); const quoted = await provenance.stage({ key: 'preference:literal', category: 'preference', title: 'Literal command preference', fact: 'The literal user submission is /project-command.', userQuote: '/project-command' }); assert('an exact quote from the literal submission can stage', JSON.stringify(quoted).includes('staged')); provenance.discard(); await provenance.close();
header('memory tools — optional projection failure is reported without losing state'); const projectionCandidate = { key: 'architecture:agent-construction', category: 'architecture' as const, title: 'Agent construction boundary', fact: 'Only runtime.ts constructs Agent.', evidence: { kind: 'project' as const, anchor: { path: 'AGENTS.md', line: 1, hash: '', codePoints: 33 } } }; if (state.kind !== 'ready') throw new Error('expected committed memory fixture'); const projectionState = state.state; const projection = new MemoryToolController(ROOT, 28, { commitMemory: async () => { throw new Error('projection write failed'); }, readMemory: async () => ({ state: projectionState, migrated: false }) }); projection.openTurn(4, 'save'); await projection.stage({ key: projectionCandidate.key, category: projectionCandidate.category, title: projectionCandidate.title, fact: projectionCandidate.fact, evidence: { path: 'AGENTS.md', quote: '  Only runtime.ts constructs Agent.' } }); projection.settle({ durable: true, session: 'session-tools', turn: 4, seq: 9, at: new Date().toISOString(), stopReason: 'endTurn', failure: false, partial: false }); projection.seal(true); await projection.close(); assert('projection failure status says authoritative memory remains committed', projection.status.problem?.includes('index projection degraded') === true); await rm(HOME, { recursive: true, force: true }); report();
