/** Focused offline verification of configured parent-only on-demand memory. */
import { access, mkdir, rm, writeFile } from 'node:fs/promises'; import path from 'node:path';
import { Model, type Agent, type BaseModelConfig, type Message, type ModelStreamEvent } from '@strands-agents/sdk';
import { allowAllBridge } from '../src/agent/permission.js'; import { AgentRuntime, setRuntimeModelFactoryForTest } from '../src/agent/runtime.js'; import { configPath, ConfigError, loadConfig } from '../src/config.js'; import { readMemoryState } from '../src/memory/state.js'; import { projectMemoryDir } from '../src/paths.js'; import { assert, header, ownPrivateHome, report } from './shared.js';
const HOME = ownPrivateHome('memory'); const ROOT = path.join(HOME, 'project'); await mkdir(ROOT, { recursive: true });
class OfflineModel extends Model<BaseModelConfig> { private config: BaseModelConfig = { modelId: 'offline', contextWindowLimit: 1000 }; override updateConfig(config: BaseModelConfig): void { this.config = { ...this.config, ...config }; } override getConfig(): BaseModelConfig { return this.config; } override async *stream(_messages: Message[]): AsyncIterable<ModelStreamEvent> { yield { type: 'modelMessageStartEvent', role: 'assistant' }; yield { type: 'modelContentBlockStartEvent' }; yield { type: 'modelContentBlockDeltaEvent', delta: { type: 'textDelta', text: 'done' } }; yield { type: 'modelContentBlockStopEvent' }; yield { type: 'modelMessageStopEvent', stopReason: 'endTurn' }; } }
setRuntimeModelFactoryForTest(async () => new OfflineModel());
header('memory — config remains strict and trajectory-bound'); assert('default enables memory', (await loadConfig(ROOT)).memory === true); await writeFile(configPath(ROOT), JSON.stringify({ trajectory: false })); assert('trajectory opt-out implicitly disables memory', (await loadConfig(ROOT)).memory === false); await writeFile(configPath(ROOT), JSON.stringify({ memory: true, trajectory: false })); let incompatible = ''; try { await loadConfig(ROOT); } catch (error) { incompatible = error instanceof ConfigError ? error.message : ''; } assert('explicit memory with trajectory off is invalid', incompatible.includes('memory') && incompatible.includes('trajectory'));
function runtimeAgent(runtime: AgentRuntime): Agent { return (runtime as unknown as { agent: Agent }).agent; } async function runtimeFor(config: Record<string, unknown>): Promise<AgentRuntime> { await writeFile(configPath(ROOT), JSON.stringify(config)); return AgentRuntime.create({ projectRoot: ROOT, session: { kind: 'new' }, permissionBridge: allowAllBridge }); }
header('memory — parent-only tools replace ambient prompt injection'); const runtime = await runtimeFor({ permissionMode: 'yolo' }); const names = runtime.info.toolNames; assert('enabled runtime exposes both parent tools', names.includes('memory_recall') && names.includes('memory_save')); const prompt = JSON.stringify(runtimeAgent(runtime).systemPrompt); assert('complete memory archive is not ambient system context', !prompt.includes('<learned-memory>')); assert('controller status exists without creating state', runtime.memoryStatus !== undefined); let exists = true; try { await access(projectMemoryDir(ROOT)); } catch { exists = false; } assert('startup creates no memory state', !exists); await runtime.shutdown();
const off = await runtimeFor({ memory: false }); assert('memory false exposes no tools or controller', !off.info.toolNames.includes('memory_recall') && !off.info.toolNames.includes('memory_save') && off.memoryStatus === undefined); assert('memory false management refuses locally', !(await off.manageMemory('/memory remember no-write')).changed); await off.shutdown();
header('memory — a refused turn discards its staging; only endTurn commits (SRF-030)'); class SaveThenStopModel extends Model<BaseModelConfig> { private config: BaseModelConfig = { modelId: 'offline', contextWindowLimit: 1000 }; calls = 0; constructor(private readonly stops: Array<'contentFiltered' | 'endTurn'>) { super(); } override updateConfig(config: BaseModelConfig): void { this.config = { ...this.config, ...config }; } override getConfig(): BaseModelConfig { return this.config; } override async *stream(messages: Message[]): AsyncIterable<ModelStreamEvent> { this.calls += 1; const answeringTool = messages.at(-1)?.content.some((block) => block.type === 'toolResultBlock') === true; yield { type: 'modelMessageStartEvent', role: 'assistant' }; if (!answeringTool) { yield { type: 'modelContentBlockStartEvent', start: { type: 'toolUseStart', name: 'memory_save', toolUseId: `save-${this.calls}` } }; yield { type: 'modelContentBlockDeltaEvent', delta: { type: 'toolUseInputDelta', input: JSON.stringify({ key: 'architecture:agent-construction', category: 'architecture', title: 'Agent construction boundary', fact: 'Only runtime.ts constructs Agent.', evidence: { path: 'NOTES.md', quote: 'Only runtime.ts constructs Agent.' } }) } }; yield { type: 'modelContentBlockStopEvent' }; yield { type: 'modelMessageStopEvent', stopReason: 'toolUse' }; return; } yield { type: 'modelContentBlockStartEvent' }; yield { type: 'modelContentBlockDeltaEvent', delta: { type: 'textDelta', text: 'I can help with' } }; yield { type: 'modelContentBlockStopEvent' }; yield { type: 'modelMessageStopEvent', stopReason: this.stops.shift() ?? 'endTurn' }; } }
// The SDK ends a refusal-class turn normally (SRF-029), and SRF-030 catalogues its prompt for `/rewind` — but `AgentRuntime.send` still seals memory on `completed` (endTurn) only, so a save staged in the refused turn never commits; the same staging under endTurn does.
await writeFile(path.join(ROOT, 'NOTES.md'), 'Only runtime.ts constructs Agent.\n'); const stopModel = new SaveThenStopModel(['contentFiltered', 'endTurn']); setRuntimeModelFactoryForTest(async () => stopModel); const stopRuntime = await runtimeFor({ permissionMode: 'yolo' }); const stops: string[] = []; for await (const event of stopRuntime.send('remember the boundary')) { if (event.type === 'agentResultEvent') stops.push(event.result.stopReason); } assert('the refused turn ran memory_save and ended with the refusal-class stop', stops.join('|') === 'contentFiltered' && stopModel.calls === 2); assert('a memory_save staged during a refused turn is discarded — seal stays endTurn-only', (await readMemoryState(ROOT)).kind === 'absent'); for await (const event of stopRuntime.send('remember the boundary again')) { if (event.type === 'agentResultEvent') stops.push(event.result.stopReason); } await stopRuntime.shutdown(); const committed = await readMemoryState(ROOT); assert('the same staging under endTurn commits after durable settlement', stops.join('|') === 'contentFiltered|endTurn' && stopModel.calls === 4 && committed.kind === 'ready' && committed.state.generated.length === 1); setRuntimeModelFactoryForTest(async () => new OfflineModel());
const trajectoryOff = await runtimeFor({ trajectory: false }); assert('trajectory-disabled runtime exposes no memory tools', !trajectoryOff.info.toolNames.includes('memory_recall') && trajectoryOff.memoryStatus === undefined); await trajectoryOff.shutdown(); setRuntimeModelFactoryForTest(undefined); await rm(HOME, { recursive: true, force: true }); report();
